# Netlify config file

# Cache
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"

# For SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
