export enum types {
  'GET_USER_PALETTES_SUCCESS' = 'GET_USER_PALETTES_SUCCESS',
  'GET_USER_PALETTES_FAILURE' = 'GET_USER_PALETTES_FAILURE',

  'GET_USER_LIKES_SUCCESS' = 'GET_USER_LIKES_SUCCESS',
  'GET_USER_LIKES_FAILURE' = 'GET_USER_LIKES_FAILURE',

  'CREATE_PALETTE_SUCCESS' = 'CREATE_PALETTE_SUCCESS',
  'CREATE_PALETTE_FAILURE' = 'CREATE_PALETTE_FAILURE',

  'GET_POP_PALETTES_SUCCESS' = 'GET_POP_PALETTES_SUCCESS',
  'GET_NEW_PALETTES_SUCCESS' = 'GET_NEW_PALETTES_SUCCESS',
  'GET_PALETTES_FAILURE' = 'GET_PALETTES_FAILURE',

  'LIKE_PALETTE_SUCCESS' = 'LIKE_PALETTE_SUCCESS',
  'LIKE_PALETTE_FAILURE' = 'LIKE_PALETTE_FAILURE',

  'UNLIKE_PALETTE_SUCCESS' = 'UNLIKE_PALETTE_SUCCESS',
  'UNLIKE_PALETTE_FAILURE' = 'UNLIKE_PALETTE_FAILURE',

  'GET_PALETTE_SUCCESS' = 'GET_PALETTE_SUCCESS',
  'GET_PALETTE_FAILURE' = 'GET_PALETTE_FAILURE',

  'DELETE_PALETTE_SUCCESS' = 'DELETE_PALETTE_SUCCESS',
  'DELETE_PALETTE_FAILURE' = 'DELETE_PALETTE_FAILURE',
}

export enum actionTypes {
  'createPalette' = 'createPalette',
  'getPalette' = 'getPalette',
  'deletePalette' = 'deletePalette',
  'getPalettes' = 'getPalettes',
  'likePalette' = 'likePalette',
  'unlikePalette' = 'unlikePalette',
  'getUserPalettes' = 'getUserPalettes',
}
